### ISSUE TITLE
How to switch between Atari and Amiga

### ISSUE THREAD

**Issue by mamejay** [jjmz/Atari-Quadrature-USB-Mouse-Adapter#1]
Hello there. I just discovered this project.  I see that you mention Amiga and Atari but how do you switch between the two?
On the schematic in the DOCS folder I can see a TP2 which I suspect you may need to pull high or low.
Can you confirm what needs to be done?  I will to make one of these and have it support both systems..

Thanks

**Comment by jjmz** [comment]
True, I ~~habe~~ have been using tp2 as serial output for debug in the beginning, but now ground it to use amiga mode. Sorry for late answer....

**Comment by mamejay** [comment]
thank you!!
